### ISSUE TITLE
Could not find a declaration file type

### ISSUE THREAD

**Issue by valefumiwlf46** [theLAZYmd/react-google-calendar#1]
Missing file defined in package.json ("types": "./lib/index.d/ts")

`Could not find a declaration file for module 'reactjs-google-calendar'. '.../node_modules/reactjs-google-calendar/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/reactjs-google-calendar` if it exists or add a new declaration (.d.ts) file containing `declare module 'reactjs-google-calendar';`ts(7016)`

**Comment by aloysiuslip** [comment]
Fixed with rewrite https://github.com/theLAZYmd/react-google-calendar/commit/5951865137231e54831cd219cf09a795e4122703

**Comment by theLAZYmd** [comment]
Fixed with rewrite https://github.com/theLAZYmd/react-google-calendar/commit/5951865137231e54831cd219cf09a795e4122703
