### ISSUE TITLE
Demo seems to be not working.

### ISSUE THREAD

**Issue by JasonHoku** [theLAZYmd/react-google-calendar#2]
Link from homepage: https://oxfordunichess.github.io/oucc-frontend/termcard

Browsers tried: Chrome, Firefox

**Comment by oyeanuj** [comment]
Also came here to report this. @theLAZYmd any place where we could see a demo or this component in action?

thanks so much for creating this!

**Comment by theLAZYmd** [comment]
Fixed with documentation update https://github.com/theLAZYmd/react-google-calendar/commit/63f23856b1357a15a93317c7f51c7a133e794167 checkout the new README page!
